// lit-client/src/showVendedor.ts
import { html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { PageBase } from './pageBase';
import { apiGetVendedor } from '@lacorazon/post-client';
import './form';
import './popups';
import './accordion';

@customElement('show-vendedor')
export class ShowVendedor extends PageBase<Vendedor> {
  @property()
  idVendedor?: ID;

  override dataLoader() {
    return apiGetVendedor(this.idVendedor!);
  }

  override pageBody(data: Vendedor) {
    return html`
      <h1>Venta</h1>
      <form-wrapper>
        <text-field
          label="Nombre"
          name="nombre"
          value=${data.nombre}
          placeholder="Nombre"
          readonly
        ></text-field>
        <email-field
          label="Email"
          name="email"
          value=${data.email || '-'}
          placeholder="Email"
          readonly
        ></email-field>
      </form-wrapper>
      <accordion-base>
        <accordion-panel
          name="ventas"
          heading="Ventas"
          .content=${html`<list-ventas idVendedor=${this.idVendedor}`}
        ></accordion-panel>
        <accordion-panel
          name="consigna"
          heading="Consigna"
          .content=${html`<h2>
            Aquí debería estar la información de libros en consigna
          </h2>`}
        ></accordion-panel>
      </accordion-base>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'show-vendedor': ShowVendedor;
  }
}

// preact-client/src/routes/vendedor/ShowVendedor.tsx
import { h, FunctionComponent } from 'preact';
import { Alert } from 'react-bootstrap';

// import { TextField, EmailField } from '@lacorazon/lit-form';
import Page from 'components/Page';
import { Loading } from 'components/Modals';
import { Accordion, AccordionPanel } from 'components/Accordion';
// import ListVentas from 'Components/ventas/ListVentas';

import { useQuery } from 'react-query';
import { apiGetVendedor } from '@lacorazon/post-client';

import 'preactDeclarations';

export const ShowUser: FunctionComponent<{ id: ID }> = ({ id }) => {
  const {
    isLoading,
    isError,
    error,
    data: vendedor,
  } = useQuery<Vendedor, Error>(['vendedor', id], () => apiGetVendedor(id));

  if (isError) return <Alert variant="warning">{error.message}</Alert>;
  if (isLoading) return <Loading>Cargando vendedor</Loading>;

  return (
    <Page
      title={`Vendedor - ${vendedor ? vendedor.nombre : '??'}`}
      heading={`Vendedor`}
    >
      <form-wrapper>
        <text-field
          label="Nombre"
          name="nombre"
          value={vendedor?.nombre}
          placeholder="Nombre"
          readonly
        />
        <email-field
          label="Email"
          name="email"
          value={vendedor?.email || '-'}
          placeholder="Email"
          readonly
        />
      </form-wrapper>
      <Accordion>
        <AccordionPanel label="Ventas" name="ventas">
          {/* <ListVentas idVendedor={id} nombreVendedor={vendedor.nombre} wide /> */}
        </AccordionPanel>
        <AccordionPanel label="Consigna" name="consigna">
          Aquí irían los libros que este vendedor tiene en consigna en las
          librerías
        </AccordionPanel>
      </Accordion>
    </Page>
  );
};

export default ShowUser;
