// react-client-swr/src/components/ventas/EditVenta.tsx
import { useNavigate } from 'react-router-dom';
import { Alert } from 'react-bootstrap';

import Page from 'components/Page';
import { DetailsButtonSet } from 'components/Buttons';
import { Loading } from 'components/Modals';
import { useModals } from 'providers/Modals';

import { formatDate } from 'utils';

import { useGetVenta } from 'dataHooks/useVentas';
import { useListVendedores } from 'dataHooks/useVendedores';

import {
  FormWrapper,
  FormSubmitEvent,
  DateField,
  TextField,
  SelectField,
  NumberField,
  CurrencyField,
  BooleanField,
} from '@lacorazon/lit-react-integration';

export const EditVenta = ({ id }: { id: ID }) => {
  const navigate = useNavigate();
  const { venta, createVenta, updateVenta, deleteVenta } = useGetVenta(id);

  const { vendedores } = useListVendedores();

  const { confirmDelete } = useModals();

  // All hooks executed, now I can branch
  if (!venta) return <Loading>Cargando venta</Loading>;
  if (!vendedores) return <Loading>Cargando ventas</Loading>;

  const onDeleteClick = () => {
    if (!venta) return;
    confirmDelete(`la venta del ${formatDate(venta.fecha)}`, () =>
      deleteVenta().then(() => navigate('/ventas', { replace: true }))
    );
  };

  const onSubmit = (ev: FormSubmitEvent) => {
    const { precioTotal, ...values } = ev.wrapper.values as Venta & {
      precioTotal: number;
    };
    if (id) {
      updateVenta({ ...values, id });
    } else {
      createVenta({ ...values }).then(({ id }) =>
        navigate(`/venta/edit/${id}`, { replace: true })
      );
    }
  };
  return (
    <Page
      title={`Venta - ${venta ? formatDate(venta.fecha) : 'nuevo'}`}
      heading={`${id ? 'Edit' : 'Add'} Venta`}
    >
      {venta ? (
        <FormWrapper onFormSubmit={onSubmit}>
          <form>
            <DateField
              label="Fecha"
              name="fecha"
              value={venta.fecha}
            ></DateField>
            <TextField
              label="Concepto"
              name="concepto"
              value={venta.concepto}
            />
            <SelectField
              label="Vendedor"
              name="idVendedor"
              labelFieldName="nombre"
              valueFieldName="id"
              nullLabel="--"
              options={vendedores as unknown as AnyRow[]}
              value={String(venta.idVendedor)}
            />
            <NumberField
              label="Cantidad"
              name="cantidad"
              value={venta.cantidad}
            />
            <CurrencyField
              label="Precio Unitario"
              name="precioUnitario"
              value={venta.precioUnitario}
            />
            <BooleanField checkLabel="IVA" name="iva" checked={!!venta.iva} />
            <CurrencyField
              label="Precio Total"
              name="precioTotal"
              value={(venta.cantidad || 0) * (venta.precioUnitario || 0)}
            />
            <DetailsButtonSet isNew={!id} onDelete={onDeleteClick} />
          </form>
        </FormWrapper>
      ) : id ? (
        <Alert color="danger">El usuario no existe o fue borrado</Alert>
      ) : null}
    </Page>
  );
};

export default EditVenta;

// lit-client/src/editVenta.ts
import { html } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import { Ref, createRef, ref } from 'lit/directives/ref.js';
import { PageBase } from './pageBase';
import { router } from './utils';
import {
  apiGetVenta,
  apiCreateVenta,
  apiUpdateVenta,
  apiListVendedores,
} from '@lacorazon/post-client';
import {
  FormSubmitEvent,
  FormChangedEvent,
  NumberField,
} from '@lacorazon/lit-form';
import './popups';

@customElement('edit-venta')
export class EditVenta extends PageBase<VentaYVendedor> {
  @property()
  idVenta?: ID;

  @state()
  _options: AnyRow[] = [];

  override dataLoader() {
    return apiListVendedores()
      .then((data) => {
        this._options = data;
      }, this.apiCatch)
      .then(() => apiGetVenta(this.idVenta!));
  }

  submit(ev: FormSubmitEvent) {
    const data = ev.wrapper.values;
    this._loading = true;
    if (this.idVenta) {
      apiUpdateVenta({ id: this.idVenta, ...data } as Venta).then(
        this.apiThen,
        this.apiCatch
      );
    } else {
      apiCreateVenta(data as Venta).then((resp) => {
        router.replace(`/venta/edit/${resp.id}`);
      }, this.apiCatch);
    }
  }

  protected precioTotalFieldRef: Ref<NumberField> = createRef();

  formChanged(ev: FormChangedEvent) {
    if (ev.name === 'cantidad' || ev.name === 'precioUnitario') {
      const precioTotalField = this.precioTotalFieldRef.value;
      if (precioTotalField) {
        const { cantidad, precioUnitario } = ev.wrapper.values as Venta;
        precioTotalField.value = (cantidad ?? 0) * (precioUnitario ?? 0);
      }
    }
  }

  renderForm(data: VentaYVendedor) {
    return html`
      <form-wrapper @formSubmit=${this.submit} @formChanged=${this.formChanged}
        ><form>
          <date-field
            label="Fecha"
            name="fecha"
            .value=${data.fecha}
          ></date-field>
          <text-field
            label="Concepto"
            name="concepto"
            value=${data.concepto || ''}
          ></text-field>
          <select-field
            label="Vendedor"
            name="idVendedor"
            value=${String(data.idVendedor) || ''}
            labelFieldName="nombre"
            valueFieldName="id"
            .options=${this._options}
          >
          </select-field>
          <number-field
            label="Cantidad"
            name="cantidad"
            value=${data.cantidad || 0}
          ></number-field>
          <currency-field
            label="Precio Unitario"
            name="precioUnitario"
            value=${data.precioUnitario || 0}
          ></currency-field>
          <boolean-field
            checkLabel="IVA"
            name="iva"
            ?checked=${data.iva}
          ></boolean-field>
          <currency-field
            label="Precio Total"
            value=${(data.cantidad || 0) * (data.precioUnitario || 0)}
            readonly
            ${ref(this.precioTotalFieldRef)}
          ></currency-field>
          <button type="submit" class="btn btn-primary">Aceptar</button>
        </form>
      </form-wrapper>
    `;
  }
  override pageBody(data: VentaYVendedor) {
    return html`
      <h1>Ventas</h1>
      ${this.renderForm(
        this.idVenta
          ? data
          : ({
              id: 0,
              concepto: '',
              fecha: new Date(),
              idVendedor: 0,
              cantidad: 1,
              precioUnitario: 12,
              iva: false,
            } as VentaYVendedor)
      )}
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'edit-venta': EditVenta;
  }
}
