// react-client-swr/src/components/vendedor/ListVendedores.tsx
import { ReactEventHandler } from 'react';
import { useNavigate } from 'react-router-dom';
import { Table, Button, Alert } from 'react-bootstrap';
import { useListVendedores } from 'dataHooks/useVendedores';
import { TableRowButtons, TableRowActionHandler } from 'components/Buttons';
import Page from 'components/Page';
import { Loading } from 'components/Modals';
import { useModals } from 'providers/Modals';

const ListVendedores = () => {
  const navigate = useNavigate();
  const { data: vendedores, error, deleteVendedor } = useListVendedores();

  const { confirmDelete } = useModals();

  if (error) return <Alert color="danger">{error}</Alert>;
  if (!vendedores) return <Loading>Cargando vendedores</Loading>;

  const onAdd: ReactEventHandler<HTMLButtonElement> = (ev) => {
    ev.stopPropagation();
    navigate(`/vendedor/new`);
  };

  const rowActionsHandler: TableRowActionHandler = (action, id, descr) => {
    switch (action) {
      case 'show':
        navigate(`/vendedor/${id}`);
        break;
      case 'edit':
        navigate(`/vendedor/edit/${id}`);
        break;
      case 'delete':
        confirmDelete(`al usuario ${descr}`, () => deleteVendedor(id));
        break;
    }
  };

  const rowVendedor = (vendedor: Vendedor) => {
    const id = vendedor.id;
    return (
      <tr key={id}>
        <td>{vendedor.nombre}</td>
        <td>{vendedor.email}</td>
        <td className="text-center">
          <TableRowButtons
            onClick={rowActionsHandler}
            id={id}
            descr={vendedor.nombre}
          />
        </td>
      </tr>
    );
  };

  return (
    <Page title="Vendedores" heading="Vendedores">
      {vendedores && (
        <Table striped hover size="sm" responsive bordered>
          <thead>
            <tr>
              <th>Nombre</th>
              <th>E-mail</th>
              <th className="text-center">
                <Button onClick={onAdd} variant="primary" title="Agregar">
                  <icon-add-person>Agregar</icon-add-person>
                </Button>
              </th>
            </tr>
          </thead>
          <tbody>{(vendedores || []).map(rowVendedor)}</tbody>
        </Table>
      )}
    </Page>
  );
};

export default ListVendedores;

// lit-client/src/listVendedores.ts
import './icons';
import './popups';
import { html } from 'lit';
import { customElement, state } from 'lit/decorators.js';
import { repeat } from 'lit/directives/repeat.js';

import { PageBase } from './pageBase';

import { apiListVendedores, apiRemoveVendedor } from './api';
import { getClosest, getTarget, router } from './utils';
import { ConfirmaEvent } from './popups';

const renderRow = (row: Vendedor) => html`
  <tr data-id=${row.id}>
    <td title="Ver detalles" data-action="show">
      <a href="#">${row.nombre}</a>
    </td>
    <td>${row.email}</td>
    <td class="text-center">
      <div class="btn-group btn-group-sm">
        <button
          class="btn btn-outline-secondary"
          data-action="edit"
          title="Modificar"
        >
          <icon-pencil></icon-pencil>
        </button>
        <button
          class="btn btn-outline-danger"
          data-action="delete"
          title="Borrar"
        >
          <icon-trash></icon-trash>
        </button>
      </div>
    </td>
  </tr>
`;

@customElement('list-vendedores')
export class ListVendedores extends PageBase<Vendedor[]> {
  @state()
  private _ask = false;

  private _id?: ID;

  override dataLoader() {
    return apiListVendedores();
  }
  private clickListener(ev: Event) {
    const $t = getTarget(ev);
    const action = getClosest($t, '[data-action]')?.dataset.action;
    if (action) {
      const id = getClosest($t, 'tr').dataset.id;
      this._id = id;
      switch (action) {
        case 'add':
          router.push('/vendedor/new');
          break;
        case 'show':
          router.push(`/vendedor/${id}`);
          break;
        case 'edit':
          router.push(`/vendedor/edit/${id}`);
          break;
        case 'delete':
          this._ask = true;
          break;
      }
    }
  }

  private doDelete(ev: ConfirmaEvent) {
    this._ask = false;
    if (ev.confirma) {
      apiRemoveVendedor(this._id!).then(
        () => router.replace(`/vendedores`, true),
        this.apiCatch
      );
    }
  }

  override pageBody(data: Vendedor[]) {
    return html`
      <confirma-dialog
        ?show=${this._ask}
        msg="¿Quiere borrar este vendedor?"
        danger
        @confirmaEvent=${this.doDelete}
      ></confirma-dialog>
      <h1>Vendedores</h1>
      <table
        class="table table-striped table-hover table-bordered table-responsive table-sm"
        @click="${this.clickListener}"
      >
        <thead class="bg-secondary text-white border border-dark">
          <tr>
            <th>Nombre</th>
            <th>E-mail</th>
            <th class="text-center">
              <button
                type="button"
                class="btn btn-primary"
                data-action="add"
                title="Agregar"
              >
                <icon-person></icon-person>
              </button>
            </th>
          </tr>
        </thead>
        <tbody>
          ${repeat(data, (data) => data.id, renderRow)}
        </tbody>
      </table>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'list-vendedores': ListVendedores;
  }
}
