// react-client-swr/src/components/ventas/ShowVenta.tsx
import Page from 'components/Page';
import { Loading } from 'components/Modals';

import { useGetVenta } from 'dataHooks/useVentas';
import {
  FormWrapper,
  DateField,
  TextField,
  NumberField,
  CurrencyField,
  BooleanField,
} from '@lacorazon/lit-form-react';

import { formatDate } from 'utils';

const ShowVenta = ({ id }: { id: ID }) => {
  const { data: venta } = useGetVenta(id);

  if (!venta) return <Loading>Cargando venta</Loading>;

  return (
    <Page
      title={`Venta - ${venta ? formatDate(venta.fecha) : '??'}`}
      heading={`Venta`}
    >
      <FormWrapper>
        <DateField label="Fecha" name="fecha" value={venta?.fecha} readonly />
        <TextField
          label="Concepto"
          name="concepto"
          value={venta?.concepto || ''}
          readonly
        />
        <TextField
          label="Vendedor"
          name="vendedor"
          value={venta?.vendedor || '-'}
          readonly
        />
        <NumberField
          label="Cantidad"
          name="cantidad"
          value={venta?.cantidad || 0}
          readonly
        />
        <CurrencyField
          label="Precio Unitario"
          name="precioUnitario"
          value={venta?.precioUnitario || 0}
          readonly
        />
        <BooleanField
          checkLabel="IVA"
          name="iva"
          value={!!venta?.iva}
          readonly
        />
        <CurrencyField
          label="Precio Total"
          name="precioTotal"
          value={(venta?.cantidad || 0) * (venta?.precioUnitario || 0)}
          readonly
        />
      </FormWrapper>
    </Page>
  );
};

export default ShowVenta;

// lit-client/src/showVenta.ts
import { html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { PageBase } from './pageBase';
import { apiGetVenta } from '@lacorazon/post-client';
import '@lacorazon/lit-form';
import './popups';

@customElement('show-venta')
export class ShowVenta extends PageBase<VentaYVendedor> {
  @property()
  idVenta?: ID;

  override dataLoader() {
    return apiGetVenta(this.idVenta!);
  }

  override pageBody(data: VentaYVendedor) {
    return html`
      <h1>Ventas</h1>
      <form-wrapper>
        <date-field
          label="Fecha"
          name="fecha"
          .value=${data.fecha}
          readonly
        ></date-field>
        <text-field
          label="Concepto"
          name="concepto"
          value=${data.concepto || ''}
          readonly
        ></text-field>
        <text-field
          label="Vendedor"
          name="vendedor"
          value=${data.vendedor || '-'}
          readonly
        ></text-field>
        <number-field
          label="Cantidad"
          name="cantidad"
          value=${data.cantidad || 0}
          readonly
        ></number-field>
        <currency-field
          label="Precio Unitario"
          name="precioUnitario"
          value=${data.precioUnitario || 0}
          readonly
        ></currency-field>
        <boolean-field
          checkLabel="IVA"
          name="iva"
          .value=${!!data.iva}
          readonly
        ></boolean-field>
        <currency-field
          label="Precio Total"
          name="precioTotal"
          value=${(data.cantidad || 0) * (data.precioUnitario || 0)}
          readonly
        ></currency-field>
      </form-wrapper>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'show-venta': ShowVenta;
  }
}
