// lit-client/src/listVendedores.ts
import './icons';
import './popups';
import { LitElement, html } from 'lit';
import { customElement, state } from 'lit/decorators.js';
import { repeat } from 'lit/directives/repeat.js';
import { BootBase } from './bootstrapBase';
import { ApiTaskListVendedores, apiRemoveVendedor } from './api';
import { getClosest, getTarget, router } from './utils';
import { ConfirmaEvent } from './popups';

const renderRow = (row: Vendedor) => html`
  <tr data-id=${row.id}>
    <td title="Ver detalles" data-action="show">
      <a href="#">${row.nombre}</a>
    </td>
    <td>${row.email}</td>
    <td class="text-center">
      <div class="btn-group btn-group-sm">
        <button
          class="btn btn-outline-secondary"
          data-action="edit"
          title="Modificar"
        >
          <icon-pencil></icon-pencil>
        </button>
        <button
          class="btn btn-outline-danger"
          data-action="delete"
          title="Borrar"
        >
          <icon-trash></icon-trash>
        </button>
      </div>
    </td>
  </tr>
`;

@customElement('list-vendedores')
export class ListVendedores extends LitElement {
  static override readonly styles = [BootBase.styles];

  private apiListVendedores = new ApiTaskListVendedores(this);

  @state()
  private _ask = false;

  @state()
  private _error?: string;

  private _id?: ID;

  private clickListener(ev: Event) {
    const $t = getTarget(ev);
    const action = getClosest($t, '[data-action]')?.dataset.action;
    if (action) {
      const id = getClosest($t, 'tr').dataset.id;
      this._id = id;
      switch (action) {
        case 'add':
          router.push('/vendedor/new');
          break;
        case 'show':
          router.push(`/vendedor/${id}`);
          break;
        case 'edit':
          router.push(`/vendedor/edit/${id}`);
          break;
        case 'delete':
          this._ask = true;
          break;
      }
    }
  }

  private doDelete(ev: ConfirmaEvent) {
    this._ask = false;
    if (ev.confirma) {
      apiRemoveVendedor(this._id!)
        .then(() => router.replace(`/vendedores`, true))
        .catch((error) => {
          this._error = error.toString();
        });
    }
  }

  override render() {
    return html`
      <error-card msg=${this._error || ''}></error-card>
      <confirma-dialog
        ?show=${this._ask}
        msg="¿Quiere borrar este vendedor?"
        danger
        @confirmaEvent=${this.doDelete}
      ></confirma-dialog>
      <h1>Vendedores</h1>
      <table
        class="table table-striped table-hover table-bordered table-responsive table-sm"
        @click="${this.clickListener}"
      >
        <thead class="bg-secondary text-white border border-dark">
          <tr>
            <th>Nombre</th>
            <th>E-mail</th>
            <th class="text-center">
              <button
                type="button"
                class="btn btn-primary"
                data-action="add"
                title="Agregar"
              >
                <icon-person></icon-person>
              </button>
            </th>
          </tr>
        </thead>
        <tbody>
          ${this.apiListVendedores.render({
            initial: () => html`<p>Inicial</p>`,
            pending: () => html`<loading-card></loading-card>`,
            // @ts-ignore
            complete: (data) => repeat(data, (data) => data.id, renderRow),
            error: (error) =>
              html`<error-card
                .msg=${(error as Error).toString()}
              ></error-card>`,
          })}
        </tbody>
      </table>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'list-vendedores': ListVendedores;
  }
}

// preact-client/src/components/vendedor/ListVendedores.tsx
import { h } from 'preact';
import { route } from 'preact-router';
import { Table, Alert, Button } from 'react-bootstrap';
import { useQuery, useMutation, useQueryClient } from 'react-query';
import { apiListVendedores, apiRemoveVendedor } from '@lacorazon/post-client';
import { TableRowButtons, TableRowActionHandler } from 'components/Buttons';
import Page from 'components/Page';
import { Loading } from 'components/Modals';
import { useModals } from 'providers/Modals';

const VENDEDORES_KEY = 'vendedores';
const ListVendedores = () => {
  const {
    isLoading,
    isError,
    error,
    data: vendedores,
  } = useQuery<Vendedor[], Error>(VENDEDORES_KEY, () => apiListVendedores());
  const queryClient = useQueryClient();

  const deleteVendedor = useMutation<null, Error, ID>(apiRemoveVendedor, {
    onSuccess: () => {
      // Invalidate and refetch
      queryClient.invalidateQueries(VENDEDORES_KEY);
    },
  });

  const { confirmDelete } = useModals();

  if (isError) return <Alert variant="warning">{error.toString()}</Alert>;
  if (isLoading) return <Loading>Cargando usuarios</Loading>;

  const onAdd = (ev: MouseEvent) => {
    ev.stopPropagation();
    route(`/vendedor/new`);
  };

  const rowActionsHandler: TableRowActionHandler = (action, id, descr) => {
    switch (action) {
      case 'show':
        route(`/vendedor/${id}`);
        break;
      case 'edit':
        route(`/vendedor/edit/${id}`);
        break;
      case 'delete':
        confirmDelete(`al usuario ${descr}`, () => deleteVendedor.mutate(id));
        break;
    }
  };

  const rowVendedor = (vendedor: Vendedor) => {
    const id = vendedor.id;
    return (
      <tr key={id}>
        <td>{vendedor.nombre}</td>
        <td>{vendedor.email}</td>
        <td class="text-center">
          <TableRowButtons
            onClick={rowActionsHandler}
            id={id}
            descr={vendedor.nombre}
          />
        </td>
      </tr>
    );
  };

  return (
    <Page title="Vendedores" heading="Vendedores">
      <Table striped hover size="sm" responsive bordered>
        <thead>
          <tr>
            <th>Nombre</th>
            <th>E-mail</th>
            <th class="text-center">
              <Button
                // @ts-ignore
                onClick={onAdd}
                variant="primary"
                title="Agregar"
              >
                <icon-add-person>Agregar</icon-add-person>
              </Button>
            </th>
          </tr>
        </thead>
        <tbody>{(vendedores || []).map(rowVendedor)}</tbody>
      </Table>
    </Page>
  );
};

export default ListVendedores;
